### ISSUE TITLE
fastq

### ISSUE THREAD

**Issue by ptoru001** [igordot/sns#13]
hi igor, 

im trying to run a wes for one sample that was processed by azenta...i uploaded all the required docs for the run and i am getting this error:

[torunp01@bigpurple-ln3 twofortyeight]$ sns/run wes
project dir: /gpfs/data/hackerlab/twofortyeight 
code dir: /gpfs/data/hackerlab/twofortyeight/sns 
logs dir: /gpfs/data/hackerlab/twofortyeight/logs-sbatch 

 fix-csv.sh ERROR: file /gpfs/data/hackerlab/twofortyeight/samples.fastq-raw.csv does not exist 

when i look at the logs-sbatch  it shows: total 0

thank you for your help
pedro

**Comment by igordot** [comment]
According to the error, you don't have `samples.fastq-raw.csv`. Did you run the `gather-fastqs` step?

**Comment by ptoru001** [comment]
i got it igor thank you..
