### ISSUE TITLE
Question Regarding PCA plot

### ISSUE THREAD

**Issue by Miladebrahim** [igordot/sns#14]
Hi Igor,

Was wondering how can i set assign each group when running rna-star-groups-dge a specific color ?
I have only two groups and I would like to choose which is red and which is blue on the PCA
Thank you

**Comment by igordot** [comment]
The colors are defined in the `deseq2-pca.R` script. Specifically:
https://github.com/igordot/sns/blob/d59a37cca875028b05f43199e54e1aa84c068b51/scripts/deseq2-pca.R#L47-L55

You can modify the script to fit your needs.
