### ISSUE TITLE
Problem with differential expression analysis

### ISSUE THREAD

**Issue by adaminjoon** [igordot/sns#15]
Hey Igor,

I am doing differential expression analysis on some DNA sequences, and I had some trouble with the sns/run rna-star-groups-dge command as it does not output any r data files or graphs for me to use. Even though I renamed the groups and there were no errors running the run rna-star or the rna-star-groups-dge command, I continuously get an empty r-data folder. Is there anything I can do?

**Comment by igordot** [comment]
If there is missing output, then something went wrong. There may not be a specific error. Have you checked the full sbatch log file?

**Comment by adaminjoon** [comment]
The sbatch log file has 13 slurm.out files in comparison to my original 12 fastq files. The other log folders look intact as well.

**Comment by igordot** [comment]
That makes sense. There should be an `rna-star` log for every sample and one for `rna-star-groups-dge`.

**Comment by adaminjoon** [comment]
Yes, I think the main issue is that I am not seeing the deseq2.dds.rds file as I want to make graphs with my data.

**Comment by igordot** [comment]
If it's missing, something went wrong. Check the full sbatch log file, especially where it ended.

**Comment by adaminjoon** [comment]
Unless you are talking about the logs-sbatch file, I do not have a full sbatch log file. However, the logs files that were outputted (logs-trimmomatic, logs-sbatch, logs-featureCounts, logs-align-star), all seem to have checked out. Was there supposed to be another logs file folder that somehow did not go through?

**Comment by igordot** [comment]
In the `logs-sbatch` directory, there is a log file for every sbatch job. The last one should be for the `rna-star-groups-dge` job.

**Comment by adaminjoon** [comment]
Hey Igor,
upon looking in the logs-sbatch directory, there seems to be a rna-star-groups-dge log file, as the date modified is about the same time I performed the rna-star-groups-dge command. In addition, there were 13 log files in the logs-sbatch directory (1 rna-star log for each of the 12 samples, and 1 rna-star-groups-dge log file).

**Comment by adaminjoon** [comment]
Hey Igor,
here attached I have a screenshot of my folder. Maybe that will help?

<img width="1353" alt="Screen Shot 2023-08-15 at 10 45 51 AM" src="https://github.com/igordot/sns/assets/67338964/2284cfc1-a43d-4067-a15d-4523c55149ed">

**Comment by igordot** [comment]
I can see you have 13 sbatch log files (as previously mentioned). The most recent one was likely generated by the `rna-star-groups-dge` job. You can view it in the terminal with `cat logs-sbatch/slurm-23702903.out`. You can also download it and open it with any text editor. If you are not sure what to look for, you can copy the contents here (or attach the whole file).

**Comment by adaminjoon** [comment]
I am looking at the file right now and there does seem to be an error. Here is the message:

Error in checkForExperimentalReplicates(object, modelMatrix) : 

  The design matrix has the same number of samples and coefficients to fit,
  so estimation of dispersion is not possible. Treating samples
  as replicates was deprecated in v1.20 and no longer supported since v1.22.

Calls: DESeq ... estimateDispersions -> .local -> checkForExperimentalReplicates
Execution halted

**Comment by adaminjoon** [comment]
Hey Igor,
I realized that my group names were different for each sample, resulting in no replicates. After altering the names, the rdata folder was populated and my problem was fixed. Thank you so much for your help!

**Comment by igordot** [comment]
Happy to hear everything is okay now.
