### ISSUE TITLE
qsub delay is too slow

### ISSUE THREAD

**Issue by stevekm** [igordot/sns#3]
The delay between submitting qsub jobs is very slow. Any chance it could be decreased a little? How much delay is really needed?

code is here:
https://github.com/igordot/sns/blob/9c02efccc8fbc4db6f3656f263a776508944e380/run#L150

**Comment by igordot** [comment]
Officially, delay is not needed at all. In practice, that may not necessarily be the case. Unless you are processing hundreds of samples at a time, the total delay is only a few minutes.
