### ISSUE TITLE
pipeline does not work if analysis directory is moved

### ISSUE THREAD

**Issue by stevekm** [igordot/sns#4]
I ran the sns pipeline in one directory, then moved the entire analysis to a different location. When trying to run more pipeline steps after moving, they break with the following error:

```
logs-qsub/sns.wes-pairs-cnv.Sample1-Sample2.o3950689: wes-pairs-cnv.sh ERROR: BAM /ifs/data/molecpathlab/scripts/snsxt/example_sns_analysis5/BAM-GATK-RA-RC/Sample1.dd.ra.rc.bam DOES NOT EXIST
```

This is presumably because the directory is no longer located at the path `/ifs/data/molecpathlab/scripts/snsxt/example_sns_analysis5`, but instead is at a different path (`/ifs/data/molecpathlab/NGS580_WES-development/example_sns_analysis_for_validation`).

I took a quick look and could not find where the program was getting this original path from, it must be hard-coded somewhere the first time it is run.

**Comment by igordot** [comment]
You shouldn't change directories. For safety, everything is based on absolute paths.

Sample-related file paths are in the `samples.*.csv` files.

**Comment by stevekm** [comment]
this makes the results un-portable and the pipeline non-reproducible, since it will no longer run if it is not in its original location.

**Comment by lavkan** [comment]
I had that issue occasionally, but just cloned sns in the new directories
again if needed.

**Comment by igordot** [comment]
It can be ported and reproduced in a new location.

Most software tools fail if interrupted in the middle of a run.

**Comment by stevekm** [comment]
This is independent of have tools running. 

Here is the workflow that produced this error:

- setup and run initial `sns` analysis: `sns/run wes`

- run paired variant calling analysis: `sns/run wes-pairs-snv`

- all `sns` jobs completed

- moved the analysis directory for collaboration & working on CNV analysis

- tried to run the CNV analysis: `sns/run wes-pairs-cnv`

- errors as described here

How can it be 'reproduced in a new location' if you can no longer run the program in a new location? Also considering that it usually takes 24-48 hours to run both `wes` and `wes-pairs-snv` routes, having to start the entire analysis from scratch just for the sake of wanting to move the parent analysis directory to a different location does not seem ideal.

**Comment by igordot** [comment]
You moved the directory before the analysis was finished. Do not move the directory in the middle of analysis.

Semantics aside, the workaround is to modify the `samples.*.csv` files where sample-related file paths are stored.
