### ISSUE TITLE
errors in wes-pairs-cnv pipeline

### ISSUE THREAD

**Issue by stevekm** [igordot/sns#5]
When trying to run the `wes-pairs-cnv` pipeline, I get the following errors:

```
logs-qsub/sns.wes-pairs-cnv.SeraCare-1to4-Positive-HapMap-B17-1267.o3950853: get-set-setting.sh ERROR: the value for setting EXP-PROBES-BED must be specified
logs-qsub/sns.wes-pairs-cnv.SeraCare-1to4-Positive-HapMap-B17-1267.o3950853: cnvs-wes-freec.sh ERROR: BED  DOES NOT EXIST
```

What .bed file is being referenced here and how should it be set?

**Comment by igordot** [comment]
You need a BED file for the probes.

**Comment by stevekm** [comment]
The .bed file was present:
```
example_sns_analysis5$ ll NGS580_targets.bed
-rw-r----- 1 kellys04 molecpathlab 565K Oct 24 17:22 NGS580_targets.bed
```

**Comment by igordot** [comment]
You need a BED file for targets (present) and probes. Two separate files.

**Comment by stevekm** [comment]
How are you supposed to set up the different .bed files so the program knows which is which?

**Comment by igordot** [comment]
The one for probes should say "probes" in the file name. In my personal experience, that has always been the case with the files provided by the manufacturer.
