### ISSUE TITLE
access to genome dir?

### ISSUE THREAD

**Issue by lgoehring** [igordot/sns#6]
Hello! I'm having a small issue with the ChIP seq peak calling. The first ChIP route worked great. I'm in the same folder and manually edited the samples.pairs.csv with IPs and inputs. I've updated the settings.txt accordingly and I'm still met with  : 

 peaks-macs.sh ERROR: genome dir /gpfs/data/igorlab/ref/hg19
 does not exist 

I can see I have access to the folder however. Is there a permissions setting? I'm new to this so I'm sure I'm missing something.

Thanks for your time!

**Comment by igordot** [comment]
Sorry you are having trouble.

How did you edit your settings.txt? Can you share the file here?

Is this only a problem for hg19 or does it happen for hg38 as well?

**Comment by lgoehring** [comment]
I edited it through filezilla. File attached. and yes just tried with hg38 and still having the same problem. Thanks!


[settings.txt](https://github.com/igordot/sns/files/8967324/settings.txt)

**Comment by igordot** [comment]
That looks okay. Just to confirm, you ran the `chip` route and it worked. The problem was only for `chip-pairs-peaks`?

Can you also share the complete log file where the error is?

**Comment by lgoehring** [comment]
Yes! ChIP route worked great. Here are the log files. Also attaching the peaks-macs in case? 

[slurm-17597688.txt](https://github.com/igordot/sns/files/8967897/slurm-17597688.txt)
[slurm-17597690.txt](https://github.c
[peaks-macs.txt](https://github.com/igordot/sns/files/8967905/peaks-macs.txt)
om/igordot/sns/files/8967898/slurm-17597690.txt)
[slurm-17597689.txt](https://github.com/igordot/sns/files/8967899/slurm-17597689.txt)
a

**Comment by lgoehring** [comment]
I also tried to copy your hg19 to the folder im running these analyses in and set that as the genome-dir but that also didn't work

**Comment by lgoehring** [comment]
that worked great! thanks!
