### ISSUE TITLE
newbie

### ISSUE THREAD

**Issue by ptoru001** [igordot/sns#7]
HI All, 

I have just run a sns/wes and a little confused of what to do next....
i am in the folder where i see : samples.fastq-raw.csv  sns
logs-sbatch  samples.fastq-clean.csv  settings.txt           summary
FASTQ-CLEAN  QC-FastQC,

I believe I added the BED file as a reference, but I am not sure..

How would I be able to retrieve these files for generating reports on these different files?

Thank you and sorry for the trouble.

**Comment by igordot** [comment]
It looks like you already started running the pipeline. Is it still running? If it stopped, did you check for errors?

**Comment by igordot** [comment]
Please check the [usage page](https://igordot.github.io/sns/usage) on how to check if it's running and how to check for errors.

**Comment by ptoru001** [comment]
Hi Igor, 

There are no issues with the WES bring run right now...how do i retrieve the files from the remote servers on to my local desktop?

Thanks
Pedro

**Comment by igordot** [comment]
These are some graphical FTP/SSH clients you can try:
- CyberDuck (multi-platform)
- Fetch (macOS)
- FileZilla (multi-platform)
- WinSCP (Windows)

**Comment by igordot** [comment]
Right. That tells you that there was an error. In the `logs-sbatch` directory, there is a log file corresponding to job 17754920. That will have more info.

**Comment by ptoru001** [comment]
Good Morning Igor,

Here are the messages from the log:

CMD: sbatch --time=99:00:00 --nodes=1 --ntasks=1 --cpus-per-task=9 --mem=72G --job-name=sns.wes.ptm1__214518 ***@***.*** --mail-type=FAIL,REQUEUE --export=NONE --wrap='bash /gpfs/home/torunp01/new_234518/sns/routes/wes.sh /gpfs/home/torunp01/new_234518 ptm1__214518'

Submitted batch job 17754920



CMD: sbatch --time=99:00:00 --nodes=1 --ntasks=1 --cpus-per-task=9 --mem=72G --job-name=sns.wes.ptm1__214518 ***@***.*** --mail-type=FAIL,REQUEUE --export=NONE --wrap='bash /gpfs/home/torunp01/new_234518/sns/routes/wes.sh /gpfs/home/torunp01/new_234518 ptm1__214518'


How would I resolve this?

Thank you
Pedro

From: igor ***@***.***>
Date: Tuesday, July 5, 2022 at 5:07 PM
To: igordot/sns ***@***.***>
Cc: Pedro Toruno ***@***.***>, Author ***@***.***>
Subject: Re: [igordot/sns] newbie (Issue #7)

Note: This message originated from outside the FIU Faculty/Staff email system.


Right. That tells you that there was an error. In the logs-sbatch directory, there is a log file corresponding to job 17754920. That will have more info.

**Comment by igordot** [comment]
That is not from a log file. I am referring to the logs in the `logs-sbatch` directory. There should be one named `slurm-17754920.out`.

**Comment by igordot** [comment]
You can read it like any other file: `cat filename`
